In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-hfr.71.23&entityid=ab0fe2bf4f3ad850371ccb9c69d78469")

In [3]:
print(df.shape)

print(df.head())

print(df.dtypes)

(105, 8)
    code  start.date    end.date  number name  ss track rf.max
0  Y1852  1852-10-07  1852-10-08       5  NaN   2     O     F1
1  Y1857  1857-09-28  1857-09-28       4  NaN   2     N     F1
2  Y1861  1861-08-17  1861-08-17       2  NaN   1     O     Nd
3  Y1864  1864-08-31  1864-08-31       3  NaN   1     S     F1
4  Y1865  1865-09-11  1865-09-11       4  NaN   2     O     F1
code          object
start.date    object
end.date      object
number         int64
name          object
ss             int64
track         object
rf.max        object
dtype: object

In [4]:
df2 = df[df['ss'] == 5]

In [5]:
df2['start.date'] = pd.to_datetime(df2['start.date'])

df2['end.date'] = pd.to_datetime(df2['end.date'])

/tmp/ipykernel_1853019/1516903933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['start.date'] = pd.to_datetime(df2['start.date'])
/tmp/ipykernel_1853019/1516903933.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['end.date'] = pd.to_datetime(df2['end.date'])

In [6]:
df2.dtypes

code                  object
start.date    datetime64[ns]
end.date      datetime64[ns]
number                 int64
name                  object
ss                     int64
track                 object
rf.max                object
dtype: object

In [7]:
df2.head()

       code start.date   end.date  number     name  ss track rf.max
76   Y1955b 1955-09-28 1955-09-28      10    Janet   5     N     F3
96   Y1980a 1980-08-07 1980-08-08       1    Allen   5     O     F3
98    Y1988 1988-09-14 1988-09-15       8  Gilbert   5     N     F3
103   Y1998 1998-10-27 1998-10-28      13    Mitch   5     S     F1

In [8]:
df2['duration'] = ((df2['end.date'] - df2['start.date']).dt.days) + 1

df2

/tmp/ipykernel_1853019/3016278975.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['duration'] = ((df2['end.date'] - df2['start.date']).dt.days) + 1

       code start.date   end.date  number     name  ss track rf.max  duration
76   Y1955b 1955-09-28 1955-09-28      10    Janet   5     N     F3         1
96   Y1980a 1980-08-07 1980-08-08       1    Allen   5     O     F3         2
98    Y1988 1988-09-14 1988-09-15       8  Gilbert   5     N     F3         2
103   Y1998 1998-10-27 1998-10-28      13    Mitch   5     S     F1         2

In [11]:
df = pd.read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-hfr.71.23&entityid=ab0fe2bf4f3ad850371ccb9c69d78469")

df2 = df[df['ss'] == 5]

pd.to_datetime(df2['start.date'])

pd.to_datetime(df2['end.date'])

76    1955-09-28
96    1980-08-08
98    1988-09-15
103   1998-10-28
Name: end.date, dtype: datetime64[ns]

In [10]:
(df.loc[df['ss'] == 5]
    .assign(duration = pd.to_datetime(df['end.date']) - pd.to_datetime(df['start.date'])))[['name', 'ss', 'duration']]

        name  ss duration
76     Janet   5   0 days
96     Allen   5   1 days
98   Gilbert   5   1 days
103    Mitch   5   1 days

In [13]:
plt.figure()

plt.scatter(pd.to_datetime(df['start_date']), df['ss'])

plt.title("Start date versus Saffir Scale")
plt.xlabel("Start Date")
plt.ylabel('Saffir-Simpson Category')

ModuleNotFoundError: No module named 'matplotlib.plot'